# Generated by Django 6.0.7 on 2026-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='monitoring_url',
            field=models.URLField(default=1, help_text='URL to monitor for health checks', max_length=500),
            preserve_default=False,
        ),
    ]
