# Generated by Django 6.0.7 on 2026-07-15 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_time', models.PositiveIntegerField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='applications.application')),
            ],
            options={
                'db_table': 'health_checks',
                'ordering': ['-checked_at'],
            },
        ),
    ]
